name: Android CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON_RELEASE }}
        run: echo "$GOOGLE_SERVICES_JSON" > venok/google-services.json

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew


      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Show APK files
        run: ls -R venok/build/outputs/apk

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: venok/build/outputs/apk/release/venok-release-unsigned.apk